baseURL: https://bonsai-lab-polimi.github.io/
languageCode: en-us
title: "BONSAI Lab"
theme: "PaperMod"

params:
  env: "production"
  title: "BONSAI Lab"
  description: "Blog of the BONSAI Lab@PoliMi."
  defaultTheme: auto
  disableThemeToggle: false
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to the BONSAI Lab Blog

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  math: true

menu:
    main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 1
        - identifier: archive
          name: Archive
          url: /archive/
          weight: 2
        - identifier: search
          name: Search
          url: /search/
          weight: 3
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 4

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary